name: Deploy to production

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Azure login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure
        uses: Azure/arm-deploy@v1
        with:
          scope: subscription
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
          region: ${{ secrets.AZURE_REGION}}
          template: ./azuredeploy.json
          parameters: >
            serviceName=WVD
            serviceLocation=westeurope
            serviceIPRangePrefix=10.10.
            localAdminPWD=${{ secrets.LOCAL_WINDOWS_ADMIN_PASSWORD }}

      - name: Run integration tests after deploy
        run: |
          IP=$(az vm show -d -g RG-WVD-backend -n VMAPP01 --query publicIps -o tsv)
          nc -zv $IP 3389
