name: Test pull request to main

on:
  pull_request:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: testing

    steps:
      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v3.x

      - name: Azure login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Checkout main branch
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Deploy current main branch to Azure
        uses: Azure/arm-deploy@v1
        with:
          scope: subscription
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
          region: ${{ secrets.AZURE_REGION}}
          template: ./azuredeploy.json
          parameters: >
            serviceName=${{ env.GITHUB_HEAD_REF_SLUG_URL }}
            serviceLocation=westeurope
            serviceIPRangePrefix=10.10.
            localAdminPWD=${{ secrets.LOCAL_WINDOWS_ADMIN_PASSWORD }}

      - name: Run integration tests before update
        run: echo ✅

      - name: Checkout pull request
        uses: actions/checkout@v2

      - name: Deploy changes to Azure
        uses: Azure/arm-deploy@v1
        with:
          scope: subscription
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
          region: ${{ secrets.AZURE_REGION}}
          template: ./azuredeploy.json
          parameters: >
            serviceName=${{ env.GITHUB_HEAD_REF_SLUG_URL }}
            serviceLocation=westeurope
            serviceIPRangePrefix=10.10.
            localAdminPWD=${{ secrets.LOCAL_WINDOWS_ADMIN_PASSWORD }}

      - name: Run integration tests again after update
        run: echo ✅

      - name: Cleanup the environment
        run: |
          az group delete -n rg-${{ env.GITHUB_HEAD_REF_SLUG_URL }}-backend-prod --yes
          az group delete -n rg-${{ env.GITHUB_HEAD_REF_SLUG_URL }}-hp-prod --yes
          az group delete -n rg-${{ env.GITHUB_HEAD_REF_SLUG_URL }}-shared-prod --yes
